#!/usr/bin/with-contenv bash

cd /app/ombi || exit

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Ombi."
redirect_cmd exec s6-setuidgid abc \
	/app/ombi/Ombi \
	--storage "/config" \
	--host http://*:3579
